// Code Generated by Sidekick is for learning and experimentation purposes only.
import express from "express";
import { prisma } from "./prisma";
import { processPayment } from "./ledger";

const app = express();
app.use(express.json());

// ROUTE 1: Check Balance
app.get("/balance/:userId", async (req, res) => {
  const wallet = await prisma.wallet.findUnique({ where: { userId: req.params.userId } });
  res.json({ balance: wallet?.balance || "0.00" });
});

// ROUTE 2: Pay
app.post("/pay", async (req, res) => {
  try {
    const { userId, amount, idempotencyKey } = req.body;
    const result = await processPayment(userId, amount, idempotencyKey);
    res.json({ message: "Success", newBalance: result.balance });
  } catch (err: any) {
    res.status(400).json({ error: err.message });
  }
});

app.listen(3000, async () => {
  try {
    await prisma.user.upsert({
      where: { email: "test@fintech.com" },
      update: {},
      create: {
        id: "user_1",
        email: "test@fintech.com",
        wallet: { create: { balance: 1000 } }
      }
    });
    console.log("Fintech Server Live on Port 3000");
  } catch (e) {
    console.error("DB Connection Error: Make sure Docker is running");
  }
});

