// Code Generated by Sidekick is for learning and experimentation purposes only.
import express from "express";
import pkg from '@prisma/client';
const { PrismaClient } = pkg;
import { PrismaPg } from '@prisma/adapter-pg';
import { Pool } from 'pg';
import { processPayment } from "./ledger.js";
import Razorpay from 'razorpay';
import crypto from 'crypto';
import 'dotenv/config';

const app = express();

// Initialize Prisma with Postgres adapter
const connectionString = process.env.DATABASE_URL;
const pool = new Pool({ connectionString });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

app.use(express.json());

// Initialize Razorpay
const razorpay = new Razorpay({
  key_id: process.env.RAZORPAY_KEY_ID!,
  key_secret: process.env.RAZORPAY_KEY_SECRET!,
});

// ROUTE 1: Check Balance (Reads from the Wallet)
app.get("/balance/:userId", async (req, res) => {
  const wallet = await prisma.wallet.findUnique({ where: { userId: req.params.userId } });
  res.json({ balance: wallet?.balance || "0.00" });
});

// ROUTE 2: Internal Pay (Phase 0 - Peer-to-Peer logic)
app.post("/pay", async (req, res) => {
  try {
    const { userId, amount, idempotencyKey } = req.body;
    const result = await processPayment(userId, amount, idempotencyKey);
    res.json({ message: "Success", newBalance: result.balance });
  } catch (err: any) {
    res.status(400).json({ error: err.message });
  }
});

// ROUTE 3: Create Order (Phase 1 - Request Money from Bank)
app.post('/create-order', async (req, res) => {
  const { amount, userId } = req.body;
  const options = {
    amount: amount * 100, // Amount in paise
    currency: "INR",
    receipt: `receipt_${userId}_${Date.now()}`,
  };

  try {
    const order = await razorpay.orders.create(options);
    res.json(order);
  } catch (error) {
    console.error("Razorpay Order Error:", error);
    res.status(500).json({ error: "Failed to create order" });
  }
});

// ROUTE 4: Verify & Ledger Sync (Phase 1 - Confirm and Deposit)
app.post('/verify-payment', async (req, res) => {
  const { razorpay_order_id, razorpay_payment_id, razorpay_signature, userId, amount } = req.body;

  // Security Check: Verify Razorpay Signature
  const sign = razorpay_order_id + "|" + razorpay_payment_id;
  const expectedSign = crypto
    .createHmac("sha256", process.env.RAZORPAY_KEY_SECRET!)
    .update(sign.toString())
    .digest("hex");

  if (razorpay_signature === expectedSign) {
    try {
        const wallet = await prisma.wallet.findUnique({ where: { userId } });
        if (!wallet) return res.status(404).json({ error: "Wallet not found" });

        // Atomic Update: Ledger entry + Wallet balance update
        await prisma.$transaction([
            prisma.ledger.create({
                data: {
                    walletId: wallet.id,
                    amount: amount, // Positive (Credit)
                    idempotencyKey: razorpay_payment_id,
                    description: "Deposit via Razorpay"
                }
            }),
            prisma.wallet.update({
                where: { userId },
                data: { balance: { increment: amount } }
            })
        ]);
        res.json({ status: "success", message: "Payment Verified & Ledger Updated" });
    } catch (e) {
        console.error("Ledger Sync Error:", e);
        res.status(500).json({ error: "Transaction Failed" });
    }
  } else {
    res.status(400).send("Invalid Signature - Fraud Attempt Blocked");
  }
});

app.listen(3000, async () => {
  try {
    // Auto-create test user for the demo
    await prisma.user.upsert({
      where: { email: "test@fintech.com" },
      update: {},
      create: {
        id: "user_1",
        email: "test@fintech.com",
        wallet: { create: { balance: 1000 } }
      }
    });
    console.log("Fintech Server Live on Port 3000");
  } catch (e) {
    console.error("Startup Error:", e);
  }
});

